version: 2.1

aliases:
  - &filter-only-main
    branches:
      only: 
        - main
        - rc
        - fix-circleci
  - &filter-main-or-release
    branches:
      only:
        - main
        - fix-circleci
    tags:
      only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/

executors:
  go:
    docker:
      - image: cimg/go:1.16.7
                       
jobs:
  build-docker-images:
    description: "Build/publish Docker images"
    parameters:
      edition:
        type: string
    executor: go
    environment:
      # Required for building cross-platform images
      DOCKER_BUILDKIT: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: CI job started
          command: ./scripts/ci-job-started.sh
      - setup_remote_docker:
          # This version is necessary for building cross-platform images
          version: 18.09.3
      - install-grabpl
      - run:
          name: Build Docker images
          command: |
            make gen-go
            make build-docker-full TAG=autonomic-tmc/customizable-grafana:dev

  codespell:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install codespell
          command: "pip install codespell"
      - run:
          # Important: all words have to be in lowercase, and separated by "\n".
          name: exclude known exceptions
          command: 'echo -e "unknwon\nreferer\nerrorstring\neror\niam\nwan\ntrough" > words_to_ignore.txt'
      - run:
          name: check documentation spelling errors
          command: "codespell -I ./words_to_ignore.txt docs/" 

  scan-docker-image:
    description: "Scans a docker image for vulnerabilities using trivy"
    parameters:
      image:
        type: string
      tag:
        type: string
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - restore_cache:
          key: vulnerability-db
      - run:
          name: Install trivy
          command: |
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )

            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            sudo mv trivy /usr/local/bin
      - run:
          name: Clear trivy cache
          command: trivy --clear-cache
      - run:
          name: Scan Docker image for unkown/low/medium vulnerabilities
          command: trivy --exit-code 0 --severity UNKNOWN,LOW,MEDIUM << parameters.image >>:<< parameters.tag >>
      - run:
          name: Scan Docker image for high/critical vulnerabilities
          command: trivy --exit-code 1 --severity HIGH,CRITICAL << parameters.image >>:<< parameters.tag >>
      - save_cache:
          key: vulnerability-db
          paths:
            - $HOME/.cache/trivy

workflows:
  build-pipeline:
    jobs:
      - codespell:
          filters: *filter-main-or-release
      - shellcheck:
          filters: *filter-main-or-release
      - build-docker-images:
          filters: *filter-main-or-release
          name: build-oss-docker-images
          edition: oss

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters: *filter-only-main
    jobs:
      - scan-docker-image:
          matrix:
            parameters:
              image: [grafana/grafana]
              tag: [latest, main]

