version: 2.1

aliases:
  - &filter-main-or-release
    branches:
      only:
        - main
        - rc

executors:
  go:
    docker:
      - image: cimg/go:1.16.7
  sonar-image:
    working_directory: /tmp/workspace
    environment:
      LANGUAGE: GOLANG
      JAVA_TOOL_OPTIONS: -Xmx1024m
    docker:
        auth:
          username: ${CS_PRIVATE_USERNAME}
          password: ${CS_PRIVATE_API_TOKEN}
                       
jobs:
  build-docker-images:
    description: "Build/publish Docker images"
    parameters:
      edition:
        type: string
    executor: go
    environment:
      # Required for building cross-platform images
      DOCKER_BUILDKIT: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: CI job started
          command: ./scripts/ci-job-started.sh
      - setup_remote_docker:
          # This version is necessary for building cross-platform images
          version: 18.09.3
      - sonarcloud-scan
      - run:
          name: Build Docker images
          command: |
            make gen-go
            make build-docker-full TAG=autonomic-tmc/customizable-grafana:dev

  codespell:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install codespell
          command: "pip install codespell"
      - run:
          # Important: all words have to be in lowercase, and separated by "\n".
          name: exclude known exceptions
          command: 'echo -e "unknwon\nreferer\nerrorstring\neror\niam\nwan\ntrough" > words_to_ignore.txt'
      - run:
          name: check documentation spelling errors
          command: "codespell -I ./words_to_ignore.txt docs/" 

workflows:
  main:
      jobs:
        - build:
            context: SonarCloud
  build-pipeline:
    jobs:
      - codespell:
          filters: *filter-main-or-release
      - build-docker-images:
          filters: *filter-main-or-release
          name: build-oss-docker-images
          edition: oss
